// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// yasir:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBOtHBk8SvQA_HKjYDI44FLjnQ4h9uow',
    appId: '1:453679320478:web:6b5ba2544e93ca82f5da8f',
    messagingSenderId: '453679320478',
    projectId: 'mywalletmanagement-b589a',
    authDomain: 'mywalletmanagement-b589a.firebaseapp.com',
    storageBucket: 'mywalletmanagement-b589a.firebasestorage.app',
    measurementId: 'G-49EKWEKGXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0CZqNGd96hE7AsKdLfdmvFNPa0EuDRcg',
    appId: '1:453679320478:android:89f1524980109f9cf5da8f',
    messagingSenderId: '453679320478',
    projectId: 'mywalletmanagement-b589a',
    storageBucket: 'mywalletmanagement-b589a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUSiemBt8uJFZ1roguAk95iGzqS748Aw',
    appId: '1:453679320478:ios:8b0cc22244341509f5da8f',
    messagingSenderId: '453679320478',
    projectId: 'mywalletmanagement-b589a',
    storageBucket: 'mywalletmanagement-b589a.firebasestorage.app',
    iosBundleId: 'com.yasir.myWalletManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUSiemBt8uJFZ1roguAk95iGzqS748Aw',
    appId: '1:453679320478:ios:8b0cc22244341509f5da8f',
    messagingSenderId: '453679320478',
    projectId: 'mywalletmanagement-b589a',
    storageBucket: 'mywalletmanagement-b589a.firebasestorage.app',
    iosBundleId: 'com.yasir.myWalletManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARBOtHBk8SvQA_HKjYDI44FLjnQ4h9uow',
    appId: '1:453679320478:web:7c9b9e5003292f16f5da8f',
    messagingSenderId: '453679320478',
    projectId: 'mywalletmanagement-b589a',
    authDomain: 'mywalletmanagement-b589a.firebaseapp.com',
    storageBucket: 'mywalletmanagement-b589a.firebasestorage.app',
    measurementId: 'G-ZNTRFQBZ0T',
  );
}
